In [1]:
import numpy as np

a = np.array([2,3,4])
b = np.array([[2,5,1],[5,6,3],[8,9,2]])

print(a)
print(b)

[2 3 4]
[[2 5 1]
 [5 6 3]
 [8 9 2]]


In [2]:
print("Numero elementos en a",a.size)   #para saber el numero de elementos en el arreglo
print("Numero elementos en b",b.size)

Numero elementos en a 3
Numero elementos en b 9


In [4]:
TempC = [12.10,13.00,17.30,18.35,20.90,19.90,19.55,19.70,18.90,18.45,15.10,15.40]
arregloTemp = np.array(TempC)     # para transformar una lista en un arreglo
print(arregloTemp+273.15)

[285.25 286.15 290.45 291.5  294.05 293.05 292.7  292.85 292.05 291.6
 288.25 288.55]


In [6]:
t = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])

for i in range(0,12,2):
    print("Valor anterior: ",t[i+1])
    t[i+1] = t[i+1]*2
    print("Valor actual: ",t[i+1])

Valor anterior:  1
Valor actual:  2
Valor anterior:  3
Valor actual:  6
Valor anterior:  5
Valor actual:  10
Valor anterior:  7
Valor actual:  14
Valor anterior:  9
Valor actual:  18
Valor anterior:  11
Valor actual:  22


In [8]:
A = np.array([[1,1],[0,1]])

for j in range(0,2):
    A[1][j] = A[1][j]*2

print(A)

[[1 1]
 [0 2]]


In [17]:
import numpy as np

semana_1 = np.array([])
semana_2 = np.array([])


Lunes_1 = float(input("Ingrese temperatura dia Lunes primera semana: "))
Martes_1 = float(input("Ingrese temperatura dia Martes primera semana: "))
Miercoles_1 = float(input("Ingrese temperatura dia Miercoles primera semana: "))
Jueves_1 = float(input("Ingrese temperatura dia Jueves primera semana: "))
 
Lunes_2 = float(input("Ingrese temperatura dia Lunes segunda semana: "))
Martes_2 = float(input("Ingrese temperatura dia Martes segunda semana: "))
Miercoles_2 = float(input("Ingrese temperatura dia Miercoles segunda semana: "))
Jueves_2 = float(input("Ingrese temperatura dia Jueves segunda semana: "))

semana_1 = np.append(semana_1,[Lunes_1,Martes_1,Miercoles_1,Jueves_1])
semana_2 = np.append(semana_2,[Lunes_2,Martes_2,Miercoles_2,Jueves_2])

promedio = np.array((semana_1+semana_2)/2)

print("Datos semana 1: ",semana_1)
print("Datos semana 2: ",semana_2)
print("Datos promedio por dia: ",promedio)

Ingrese temperatura dia Lunes primera semana:  18.5
Ingrese temperatura dia Martes primera semana:  16.7
Ingrese temperatura dia Miercoles primera semana:  19.0
Ingrese temperatura dia Jueves primera semana:  21.4
Ingrese temperatura dia Lunes segunda semana:  21.8
Ingrese temperatura dia Martes segunda semana:  22.2
Ingrese temperatura dia Miercoles segunda semana:  20.3
Ingrese temperatura dia Jueves segunda semana:  18.8


Datos semana 1:  [18.5 16.7 19.  21.4]
Datos semana 2:  [21.8 22.2 20.3 18.8]
Datos promedio por dia:  [20.15 19.45 19.65 20.1 ]


In [16]:
def promedio(a,b):
    return np.array(a+b)/2
            
semana_1 = np.array([])
semana_2 = np.array([])


Lunes_1 = float(input("Ingrese temperatura dia Lunes primera semana: "))
Martes_1 = float(input("Ingrese temperatura dia Martes primera semana: "))
Miercoles_1 = float(input("Ingrese temperatura dia Miercoles primera semana: "))
Jueves_1 = float(input("Ingrese temperatura dia Jueves primera semana: "))
 
Lunes_2 = float(input("Ingrese temperatura dia Lunes segunda semana: "))
Martes_2 = float(input("Ingrese temperatura dia Martes segunda semana: "))
Miercoles_2 = float(input("Ingrese temperatura dia Miercoles segunda semana: "))
Jueves_2 = float(input("Ingrese temperatura dia Jueves segunda semana: "))

semana_1 = np.append(semana_1,[Lunes_1,Martes_1,Miercoles_1,Jueves_1])
semana_2 = np.append(semana_2,[Lunes_2,Martes_2,Miercoles_2,Jueves_2])

a = semana_1
b = semana_2

print("Datos semana 1: ",semana_1)
print("Datos semana 2: ",semana_2)
print("Datos promedio por dia: ",promedio(a,b))

Ingrese temperatura dia Lunes primera semana:  18.5
Ingrese temperatura dia Martes primera semana:  16.7
Ingrese temperatura dia Miercoles primera semana:  19.0
Ingrese temperatura dia Jueves primera semana:  21.4
Ingrese temperatura dia Lunes segunda semana:  21.8
Ingrese temperatura dia Martes segunda semana:  22.2
Ingrese temperatura dia Miercoles segunda semana:  20.3
Ingrese temperatura dia Jueves segunda semana:  18.8


Datos semana 1:  [18.5 16.7 19.  21.4]
Datos semana 2:  [21.8 22.2 20.3 18.8]
Datos promedio por dia:  [20.15 19.45 19.65 20.1 ]
