In [2]:
import numpy as np

a = np.array([2,3,4])
b = np.array([[2,5,1],[5,6,3],[8,9,2]])

print(a)
print(b)

[2 3 4]
[[2 5 1]
 [5 6 3]
 [8 9 2]]


In [3]:
print("Elements in a",a.size)  
print("Elements in b",b.size)

Elements in a 3
Elements in b 9


In [4]:
TempC = [12.10,13.00,17.30,18.35,20.90,19.90,19.55,19.70,18.90,18.45,15.10,15.40]
arrayTemp = np.array(TempC)     
print(arrayTemp+273.15)   # to change from Celcius degrees to Kelvin

[285.25 286.15 290.45 291.5  294.05 293.05 292.7  292.85 292.05 291.6
 288.25 288.55]


In [5]:
t = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])

for i in range(0,12,2):
    print("Previous valor: ",t[i+1])
    t[i+1] = t[i+1]*2
    print("Current valor: ",t[i+1])

Previous valor:  1
Current valor:  2
Previous valor:  3
Current valor:  6
Previous valor:  5
Current valor:  10
Previous valor:  7
Current valor:  14
Previous valor:  9
Current valor:  18
Previous valor:  11
Current valor:  22


In [8]:
A = np.array([[1,1],[0,1]])

for j in range(0,2):
    A[1][j] = A[1][j]*2

print(A)

[[1 1]
 [0 2]]


In [7]:
import numpy as np  

week_1 = np.array([])
week_2 = np.array([])


monday_1 = float(input("Enter temperature for Monday first week: "))
tuesday_1 = float(input("Enter temperature for Tuesday first week: "))
wednesday_1 = float(input("Enter temperature for Wednesday first week: "))
thursday_1 = float(input("Enter temperature for Thursday first week: "))
 
monday_2 = float(input("Enter temperature for Monday second week: "))
tuesday_2 = float(input("Enter temperature for Tuesday second week: "))
wednesday_2 = float(input("Enter temperature for Wednesday second week: "))
thursday_2 = float(input("Enter temperature for Thursday second week: "))

week_1 = np.append(week_1,[monday_1,tuesday_1,wednesday_1,thursday_1])
week_2 = np.append(week_2,[monday_2,tuesday_2,wednesday_2,thursday_2])

average = np.array((week_1+week_2)/2)

print("First week data: ",week_1)
print("Second week data: ",week_2)
print("Average data per day: ",average)

Enter temperature for Monday first week:  17.3
Enter temperature for Tuesday first week:  18.7
Enter temperature for Wednesday first week:  18.2
Enter temperature for Thursday first week:  19.1
Enter temperature for Monday second week:  20.0
Enter temperature for Tuesday second week:  21.7
Enter temperature for Wednesday second week:  22.3
Enter temperature for Thursday second week:  20.8


First week data:  [17.3 18.7 18.2 19.1]
Second week data:  [20.  21.7 22.3 20.8]
Average data per day:  [18.65 20.2  20.25 19.95]


In [8]:
def average(a,b):      # the same as above but as a function
    return np.array(a+b)/2
            
week_1 = np.array([])
week_2 = np.array([])


monday_1 = float(input("Enter temperature for Monday first week: "))
tuesday_1 = float(input("Enter temperature for Tuesday first week: "))
wednesday_1 = float(input("Enter temperature for Wednesday first week: "))
thursday_1 = float(input("Enter temperature for Thursday first week: "))
 
monday_2 = float(input("Enter temperature for Monday second week: "))
tuesday_2 = float(input("Enter temperature for Tuesday second week: "))
wednesday_2 = float(input("Enter temperature for Wednesday second week: "))
thursday_2 = float(input("Enter temperature for Thursday second week: "))

week_1 = np.append(week_1,[monday_1,tuesday_1,wednesday_1,thursday_1])
week_2 = np.append(week_2,[monday_2,tuesday_2,wednesday_2,thursday_2])

a = week_1
b = week_2

print("First week data: ",week_1)
print("Second week data: ",week_2)
print("Average data per day: ",average(a,b))

Enter temperature for Monday first week:  17.3
Enter temperature for Tuesday first week:  18.7
Enter temperature for Wednesday first week:  18.2
Enter temperature for Thursday first week:  19.1
Enter temperature for Monday second week:  20.0
Enter temperature for Tuesday second week:  21.7
Enter temperature for Wednesday second week:  22.3
Enter temperature for Thursday second week:  20.8


First week data:  [17.3 18.7 18.2 19.1]
Second week data:  [20.  21.7 22.3 20.8]
Average data per day:  [18.65 20.2  20.25 19.95]
